// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg1C43pZd0mZ3iV7x64uYntAPht_I_AAI',
    appId: '1:354638570049:web:79819fff00e8500a345cc0',
    messagingSenderId: '354638570049',
    projectId: 'my-wheelease',
    authDomain: 'my-wheelease.firebaseapp.com',
    storageBucket: 'my-wheelease.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS21Ly55Fd7ibr51Dp-D3fz_oGt3yFkDY',
    appId: '1:932273484836:android:27d2f7afc512f2eb3f14b1',
    messagingSenderId: '932273484836',
    projectId: 'wheel-ease',
    storageBucket: 'wheel-ease.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvHQ5u7nXMCGIgk5X3pVJXS4bNCGw3LVk',
    appId: '1:354638570049:ios:d7614415b12c3a6d345cc0',
    messagingSenderId: '354638570049',
    projectId: 'my-wheelease',
    storageBucket: 'my-wheelease.firebasestorage.app',
    iosBundleId: 'com.example.wheelease',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvHQ5u7nXMCGIgk5X3pVJXS4bNCGw3LVk',
    appId: '1:354638570049:ios:d7614415b12c3a6d345cc0',
    messagingSenderId: '354638570049',
    projectId: 'my-wheelease',
    storageBucket: 'my-wheelease.firebasestorage.app',
    iosBundleId: 'com.example.wheelease',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDg1C43pZd0mZ3iV7x64uYntAPht_I_AAI',
    appId: '1:354638570049:web:79bdf633965bba96345cc0',
    messagingSenderId: '354638570049',
    projectId: 'my-wheelease',
    authDomain: 'my-wheelease.firebaseapp.com',
    storageBucket: 'my-wheelease.firebasestorage.app',
  );
}